apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/nginx

namespace: dev

replicas:
  - name: nginx
    count: 1

images:
  - name: nginx
    newTag: 1.25-alpine
