apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/nginx

namespace: staging

replicas:
  - name: nginx
    count: 3

images:
  - name: nginx
    newTag: "1.25"
